Hakawai/Core/HKWTextView.m
- The user will now be able to tap anywhere on the textview while mentions list is being shown
- On the tap, we dismiss the mentions list & move the cursor to the tap location
=> Hakawai: Allowing user to tap on textview while mentioning

Hakawai/Mentions/HKWMentionsPlugin.h, Hakawai/Mentions/HKWMentionsPlugin.m
- Adding the following functions to HKWMentionsStateChangeDelegate protocol:
1. mentionsPlugin:(HKWMentionsPlugin *)plugin trimmedMention:(id<HKWMentionsEntityProtocol>)entity
atLocation:(NSUInteger)location
2. mentionsPlugin:(HKWMentionsPlugin *)plugin deletedMention:(id<HKWMentionsEntityProtocol>)entity
atLocation:(NSUInteger)location
=> Hakawai: Adding functions to HKWMentionsStateChangeDelegate protocol

Hakawai.podspec, Hakawai.xcodeproj/project.pbxproj, Hakawai/Core/HKWTextView.m, HakawaiDemo/HakawaiDemo.xcodeproj/project.pbxproj, HakawaiDemo/HakawaiDemo/MentionsDemoViewController.m, HakawaiDemo/HakawaiDemo/SimpleChooserView.swift, Pods/Pods.xcodeproj/project.pbxproj
Currently if a control flow plugin is registered w/ the textView and implements the textView:shouldChangeTextInRange:replacementText: UITextFieldDelegate method, then the control flow plugin's result is returned without forwarding on to the external delegate.  This is important and correct behavior in the case where the control flow plugin denies the replacement text change, however when the control flow plugin either does not implement the delegate method or allows the text change, the external delegate should be given the option to weigh in.  This allows for more expressive behavior in the external delegate without compromising any current behavior imposed by the control flow plugin.
=> forward textView:shouldChangeTextInRange:replacementText: to externalDelegate, other proj updates

Hakawai/Mentions/HKWMentionsPlugin.m
Repro steps:
1) Add mention at beginning.
2) After the mention, add white space then 3 chars (i.e " aaa").
3) Tap on mention, type a character in the range of first 3 characters.
(You may need to move cursor position by dragging to reach at the specified location).
4) App will crash.
Fix:
- When user change the cursor position by tapping, implicit-mention's buffer string
was not being cleared when new cursor position lies in the range of mention or
just after mention.
- It resulted in an assertion failure "Logic error: prefixLength would make the location of the
mention negative".
- Fixed it by using cursorMovedWithCharacterNowPrecedingCursor() even when tapped on mention
or just after mention. It ultimately clears the implicit-mention's buffer.
=> Hakawai: FEEDUI-12763, Fixed assertion failure.

Hakawai/Core/HKWTextView+Plugins.m
Fixing a debug device build warning for unsafe usage of UInteger as a format argument.
=> Fixing a debug device build warning for unsafe usage of UInteger

Hakawai/Core/HKWTextView.h, Hakawai/Core/HKWTextView.m, HakawaiDemo/HakawaiDemo.xcodeproj/project.pbxproj, HakawaiDemo/HakawaiDemo/SimpleChooserView.swift
Upgrades demo to Swift 3.0 so we can build with 8.3.2. Also exposes `init(frame:)` and `init(frame:textContainer:)` publicly so they can be overridden in subclasses.
=> Adds new public initializers + Swift 3.0

Hakawai.podspec, Hakawai.xcodeproj/xcshareddata/xcschemes/Hakawai.xcscheme, Hakawai/Core/HKWTextView.h, HakawaiDemo/HakawaiDemo.xcodeproj/project.pbxproj, HakawaiDemo/HakawaiDemo.xcodeproj/xcshareddata/xcschemes/HakawaiDemo.xcscheme, HakawaiDemo/HakawaiDemo/Images.xcassets/AppIcon.appiconset/Contents.json, HakawaiDemo/HakawaiDemo/Images.xcassets/LaunchImage.launchimage/Contents.json, HakawaiDemo/HakawaiDemo/Info.plist, HakawaiDemo/HakawaiDemo/SimpleChooserView.swift
This requires bumping version to 5.0.0 since the nullability annotations change the method signatures in Swift.
=> Nullability Annotations + fixing warnings

Hakawai/Mentions/HKWMentionsPlugin.m
Reproduce steps:
1. Input " some text"(with one leading space but no trailing spaces) in the text view.
2. Press <kbd>ctrl</kbd>+<kbd>a</kbd> to put the caret at the beginning of the line.
3. Press <kbd>@</kbd> to trigger a mention. It doesn't work.
4. Press <kbd>Right</kbd> and <kbd>Left</kbd> and <kbd>@</kbd> again. It works this time.
There can't be a preceding mention when `location` is zero but we shouldn't return early because this call `[self.startDetectionStateMachine cursorMovedWithCharacterNowPrecedingCursor:precedingChar]` is necessary here to update the internal states of `startDetectionStateMachine`.
=> Fix mentions not working when caret is put at the beginning position in some cases

Podfile
Specta master branch does not work with xcode8, but demo app requires it. I've pointed the podfile to the xcode8 compatible branch on github.
=> Target Specta pod at Xcode8 branch

Hakawai.xcodeproj/project.pbxproj, Hakawai/Core/TextKit/HKWLayoutManager.m, HakawaiTests/HKWLayoutManagerTests.m, HakawaiTests/HKWMentionsPluginTests.m
The crash can happen when typing in particular languages, like Tamil, when characters combine and result in shorter text afterwards.
=> Fix crash in HKWLayoutManager, added unit tests for LayoutManager and MentionsPlugin

Hakawai/Mentions/HKWMentionsPlugin.m
This fixes the first issue mentioned in #60.
When the first candidate `test` is confirmed, `shouldChangeTextInRange` is called with text `test` and range `(0, 4)`. However, the text is not changed after confirmation (and after `transformTextAtRange`). So when the return value `NO` tells UIKit to revert this unconfirmed insertion, `test` gets removed. If the user selected another candidate, the text gets inserted successfully in `transformTextAtRange` and reverting will fail because the text is changed.
I rather consider this as a workaround because Hakawai seems never to take CJK input methods(which will insert unconfirmed marked text when the user is typing) into account and the second issue mentioned in #60 is much harder than this to fix without a major refactoring.
Related JIRA …
=> Fix shouldChangeTextInRange detecting text insertion with CJK input methods

Hakawai/Mentions/HKWMentionsCreationStateMachine.m
This usage of sharedApplication is the only instance of Hakawai using an API not allowed in App Extensions. On top of that, it's unnecessary to use it at all. CGRectZero works just as well here as constraints take over afterwards to correctly size the Chooser view.
=> Remove usage of sharedApplication to allow Hakawai to be used in App Extensions

Hakawai/Core/HKWTextView+Plugins.h, Hakawai/Mentions/HKWMentionsPlugin.h, Hakawai/Mentions/_HKWMentionsCreationStateMachine.h, Hakawai/Mentions/_HKWMentionsStartDetectionStateMachine.h
The warnings for this are disabled in the Hakawai xcodeproj, but consumers of this library don't usually disable these warnings, and I've been seeing several like this about the documentation:
```
.../Pods/Hakawai/Hakawai/Core/HKWTextView+Plugins.h:59:9: Parameter 'captureTouches' not found in the function declaration
```
This PR fixes all those warnings by referring to the correct param name. I suspect that some of these params should actually be renamed to the more descriptive documented name, but I'm just fixing the warnings.
=> Fix documentation param names to silence Xcode warnings

Hakawai.podspec, Hakawai.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Hakawai/Mentions/HKWMentionsCreationStateMachine.m, Hakawai/Mentions/HKWMentionsPlugin.h, Hakawai/Mentions/_HKWMentionsCreationStateMachine.h
This configuration value (off by default) will enable us to change behavior for what happens when we have a query with no results. By default, this returns the mentions state to quiescent, preventing further mentions. With the flag on, we don't cancel the mention and continue searching the next time we delete or add a character.
=> Adds configuration for shouldContinueSearchingAfterEmptyResults

Hakawai/Mentions/HKWMentionsCreationStateMachine.m, Hakawai/Mentions/HKWMentionsPlugin.h, Hakawai/Mentions/HKWMentionsPlugin.m, Hakawai/Mentions/_HKWMentionsCreationStateMachine.h, HakawaiDemo/HakawaiDemo/MentionsManager.m, HakawaiTests/HKWMentionsCreationStateMachineTest.m, HakawaiTests/Supporting Classes/HKWTDummyMentionsManager.h, HakawaiTests/Supporting Classes/HKWTDummyMentionsManager.m
Added support to trigger a fetch async call when the TextView begins editing for the first time. 
This is to allow implementers to show some initial suggestion for mentions.
Added test case to verify that **MentionManager.asyncRetrieveEntitiesForKeyString** is called with search type **HKWMentionsSearchTypeInitial** when HKWTextView begins editing.
=> Add support to trigger fetch for initial mention

Hakawai/Core/AbstractionLayer/HKWAbstractionLayer.m, Hakawai/Core/HKWTextView+Plugins.m, Hakawai/Core/HKWTextView+TextTransformation.m, Hakawai/Core/HKWTextView.m, Hakawai/Mentions/HKWMentionsCreationStateMachine.m, Hakawai/Mentions/HKWMentionsPlugin.m, Hakawai/Mentions/HKWMentionsStartDetectionStateMachine.m
clean up warning: Weak property is accessed multiple times in this method but may be unpredictably set to nil
(parentTextView, delegate, externalDelegate, stateChangeDelegate)
=> clean up warning: Weak property is accessed multiple times in this method but may be unpredictably set to nil

Hakawai/Core/HKWSimplePluginProtocol.h, Hakawai/Core/HKWTextView.m, Hakawai/Mentions/HKWMentionsPlugin.m, HakawaiTests/HKWMentionsPluginTests.m, HakawaiTests/HKWTextViewPluginTests.m
- Added support to trigger call to fetch entities, when text is inserted via dictation
- Added tests to verify the behavior for dictation
- Fixed an issue in HKWMentionsPlugin.m, which caused a crash when deleting second last character of a string
- Fixed build errors in SimpleChooserView.swift
=> ENGAGE-51063: Support Dictation search for entities

Hakawai/Mentions/HKWMentionsPlugin.m
Currently, `textViewDidChange` delegate calls are being swallowed by programmatic text changes in `advanceStateForStringInsertionAtRange`. This is most problematic when a user is typing emoji or other characters where `text.length != 1`. In my specific use case, typing a single emoji in an `HKWTextView` subclass doesn't notify my `externalDelegate` where I enable a submit button and hide a placeholder text label. This problem is also referenced in  https://github.com/linkedin/Hakawai/issues/53
Manually notify the external delegate of a change after programmatically updating the text. By not changing any logic internal to the mention plugin, this should avoid any state machine regressions.
=> Notify external delegate of change after manually inserting text.

Hakawai/Mentions/HKWMentionsPlugin.m
This bug occurs because to change `autocapitalizationType` needs call `resignFirstResponder` and `becomeFirstResponder`, when 3DTouch selecting is working and plugin call `resignFirstResponder` the method `setCursorPosition` send to window first responder, then crash app.
I removed the line `[self toggleAutocorrectAsRequiredForRange:searchRange];` to don't change `autocapitalizationType` when selecting and all funcionalities still works.
See #33
=> Fixed bug with 3DTouch Keyboard selection.

Hakawai/Core/TextKit/HKWLayoutManager.m
See #75, but `HKWRoundedRectBackgroundAttributeName` breaks in Swift when comparing attrs.
It was compared with a `const` string, so when the app and the library used different references, it was problematic. This should fix it by adding a string equality check!
Fixes #75
=> Compares HKWRoundedRectBackgroundAttributeName correctly

Hakawai.xcodeproj/project.pbxproj, Hakawai/Core/TextKit/HKWCustomAttributes.m, Hakawai/Core/TextKit/HKWLayoutManager.m
This allows us to switch back to variable comparison instead of using string equals, as this change exposes the variable externally of the library without exposing two copies of it. Fixes #75 and is a better fix than #106.
=> Exposes HKWRoundedRectBackgroundAttributeName via extern

Hakawai/Mentions/HKWMentionsPlugin.h, Hakawai/Mentions/HKWMentionsPlugin.m
Takes all other static strings defined in headers and moves them to the implementation file and exposes them via `OBJC_EXTERN`.
This helps Swift interoperability by only providing one copy of the variable, not two like was previously happening. #107 was the other instance of this already fixed. This PR changes the rest
=> Better externifies our constants for swift interoperability

Hakawai/Core/HKWTextView+TextTransformation.m, Hakawai/Core/HKWTextView.h, Hakawai/Core/HKWTextView.m, HakawaiTests/HKWMentionsPluginTests.m, HakawaiTests/HKWTextViewAttributeTransformerTests.m, HakawaiTests/HKWTextViewTextTransformerTests.m
Fix iOS QuickPath keyboard deadlock by scheduling text assignment in the main queue. 
There's also an open Apple feedback ticket,. [Open Radar](rdar://6828895)
=> Fix iOS QuickPath keyboard deadlock

Hakawai/Mentions/HKWMentionsPlugin.m, Hakawai/Mentions/HKWMentionsStartDetectionStateMachine.m
- When user types in punctuation character like opening braces, brackets, do not stall
and set ready state to trigger mention if typed in control character.
=> Adds support to trigger mention after punctuation marks like brackets, braces

Hakawai/Core/HKWControlFlowPluginProtocols.h, Hakawai/Core/HKWTextView+Plugins.m, Hakawai/Core/HKWTextView.h, Hakawai/Core/HKWTextView.m, Hakawai/Mentions/HKWMentionsCreationStateMachine.m, Hakawai/Mentions/HKWMentionsPlugin.m
Move logic during mentions from uitextviewdelegate to NSTextStorageDelegate, because textstoragedelegate actually offers us events when korean text is updated while textviewdelegate does not
This holistic solution fixes korean and maintains functionality for all other languages
it is lixed and only applies when creating or starting a mention
=> Implement korean mentions fix

Hakawai/Core/HKWTextView.h, Hakawai/Core/HKWTextView.m, Hakawai/Mentions/HKWMentionsCreationStateMachine.m
Experimenting with a change where the `selected` callback always fires prior to any textView callbacks triggered by the `createMention` workflow. This allow the HKWTextView creator to act on the mention entity prior to receiving callbacks for the mention chooser view dismissal.
=> Add flag to reverse order of mention selection delegate callbacks

Hakawai/Core/HKWTextView.h, Hakawai/Core/HKWTextView.m, Hakawai/Mentions/HKWMentionsCreationStateMachine.m, Hakawai/Mentions/HKWMentionsPlugin.m, Hakawai/Mentions/HKWMentionsStartDetectionStateMachine.m, Hakawai/Mentions/_HKWMentionsCreationStateMachine.h, Hakawai/Mentions/_HKWMentionsStartDetectionStateMachine.h
Editing the mention should trigger the typeahead again
- On removal of whitespace between control character and typed in string, it should trigger mention again
- Updated state machine, to update the flow to trigger mention
Reference PR https://github.com/aniyati/Hakawai/pull/1 view all conversation/back-forth and review comments
=> Trigger mention on whitespace removal rebased

Hakawai/Core/AbstractionLayer/HKWAbstractionLayer.m
Demo app compiles + all tests pass locally.
=> Fix "implicit conversion from enumeration type to different enumeration type" in HKWAbstractionLayer

Hakawai.podspec, Hakawai/Mentions/HKWMentionsPlugin.h, Hakawai/Mentions/HKWMentionsPluginV1.h, Hakawai/Mentions/HKWMentionsPluginV2.h
In swift, instance methods in protocols aren't recognized and you can't instantiate a class via one. Moving these to respective v1/v2 header files to enable swift portability
=> Move instance methods to classes because the cannot be in protocols

Hakawai.xcodeproj/project.pbxproj, Hakawai/Core/HKWTextView.h, Hakawai/Core/HKWTextView.m, Hakawai/HKWExternalMentionConstants.h, Hakawai/HKWExternalMentionConstants.m, Hakawai/Mentions/HKWMentionsPluginV2.h, Hakawai/Mentions/HKWMentionsPluginV2.m, HakawaiDemo/HakawaiDemo/MentionsDemoViewController.m, HakawaiTests/HKWMentionsPluginTests.m
When the user taps "@Chen" and selects entity "Chen Yuan", currently the highlighted mention text in the text view is "Chen Yuan". This PR is to implement the feature to prepend control character ('@') to mention entity text. Then the text view will display "@Chen Yuan".
The feature is implemented in the following steps:
1. Add a new parameter in HKWMentionsPluginV2's initializer to take in an NSCharacterSet of control characters to be prepended. Also add a class property for default at symbols, including English character (@) and Japanese character (＠).
2. When creating a new MentionsAttribue from the state machine, we check if the mention is triggered by a prepend-able control character, and if so, modify the text in the MentionsAttrirbute to include that control character at the …
=> Prepend control characters to mention text
